src/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path("send_login_email", views.send_login_email, name="send_login_email"),
    path("login", views.login, name="login"),
    path("logout", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
]

src/lists/urls.py
from django.contrib import admin
from django.urls import path
from lists.views import home_page, view_list, new_list, my_lists, share_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_page, name="home"),
    path("new", new_list, name="new_list"),
    path("<int:list_id>/", view_list, name="view_list"),
    path("users/<str:email>/", my_lists, name="my_lists"),
    path("<int:list_id>/share", share_list, name="share_list")
]

src/superlists/urls.py
from django.urls import include, path
from lists import views as list_views

urlpatterns = [
    path("", list_views.home_page, name="home"),
    path("lists/", include("lists.urls")),
    path("accounts/", include("accounts.urls")),
]

src/accounts/models.py
from django.db import models
import uuid


class User(models.Model):
    email = models.EmailField(primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"
    is_anonymous = False
    is_authenticated = True

class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

src/lists/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model

# Create your models here.
class List(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="lists",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    shared_with = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="shared_lists",
    )

    def get_absolute_url(self):
        return reverse("view_list", args=[self.id])


    def add(self, email):
        User = get_user_model()
        user = User.objects.get(email=email)
        self.shared_with.add(user)

    @property
    def name(self):
        return self.item_set.first().text


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    class Meta:
        ordering = ("id",)
        unique_together = ("list", "text")

    def __str__(self):
        return self.text

src/lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from lists.models import Item

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):
    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.widgets.TextInput(
                attrs={
                    "placeholder": "Enter a to-do item",
                    "class": "form-control form-control-lg",
                }
            ),
        }
        error_messages = {"text": {"required": EMPTY_ITEM_ERROR}}

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def save(self):
        return forms.models.ModelForm.save(self)

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {"text": [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

src/accounts/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib import messages, auth

from accounts.models import Token

def send_login_email(request):
    email = request.POST["email"]
    print(type(send_mail))
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(reverse("login") + "?token=" + str(token.uid))
    message_body = f"Use this link to log in:\n\n{url}"
    send_mail(
        "Your login link for Superlists",
        message_body,
        "noreply@superlists",
        [email],
    )
    messages.success(
        request,
        "Check your email, we've sent you a link you can use to log in.",
    )
    return redirect("/")


def login(request):
    if user := auth.authenticate(uid=request.GET["token"]):
        auth.login(request, user)
    else:
        messages.error(request, "Invalid login link, please request a new one")
    return redirect("/")

src/lists/views.py
from django.shortcuts import render, redirect
from lists.models import Item, List
from lists.forms import ItemForm, ExistingListItemForm
from django.contrib.auth import get_user_model


User = get_user_model()

# Create your views here.


def home_page(request):
    return render(request, "home.html", {"form": ItemForm()})


def view_list(request, list_id):
    our_list = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=our_list)
    if request.method == "POST":
        form = ExistingListItemForm(for_list=our_list, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(our_list)
    else:
        form = ExistingListItemForm(for_list=our_list)

    return render(request, "list.html", {"list": our_list, "form": form})


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        nulist = List.objects.create()
        if request.user.is_authenticated:
            nulist.owner = request.user
            nulist.save()
        form.save(for_list=nulist)
        return redirect(nulist)
    else:
        return render(request, "home.html", {"form": form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, "my_lists.html", {"owner": owner})

def share_list(request, list_id):
    my_list = List.objects.get(id=list_id)
    my_list.add(request.POST["sharee"])
    return redirect(my_list)

src/lists/templates/base.html
<html lang="en" data-bs-theme="dark">
  <head>
    <title>To-Do lists</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
      <div class="container">

        <body>
          <div class="container">

            <nav class="navbar">
              <div class="container-fluid">
                <a class="navbar-brand" href="/">Superlists</a>
                {% if user.email %}
                <a class="navbar-link" href="{% url 'my_lists' user.email %}">My lists</a>
                  <span class="navbar-text">Logged in as {{ user.email }}</span>
                  <form method="POST" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button id="id_logout" class="btn btn-outline-secondary" type="submit">Log out</button>
                  </form>
                {% else %}
                  <form method="POST" action="{% url 'send_login_email' %}">
                    <div class="input-group">
                      <label class="navbar-text me-2" for="id_email_input">
                        Enter your email to log in
                      </label>
                      <input
                        id="id_email_input"
                        name="email"
                        class="form-control"
                        placeholder="your@email.com"
                      />
                      {% csrf_token %}
                    </div>
                  </form>
                {% endif %}
              </div>
            </nav>

          {% if messages %}
            <div class="row">
              <div class="col-md-8">
                {% for message in messages %}
                  {% if message.level_tag == 'success' %}
                    <div class="alert alert-success">{{ message }}</div>
                  {% else %}
                    <div class="alert alert-warning">{{ message }}</div>
                  {% endif %}
                {% endfor %}
              </div>
            </div>
          {% endif %}

        <div class="row justify-content-center p-5 bg-body-tertiary rounded-3">
          <div class="col-lg-6 text-center">
            <h1 class="display-1 mb-4">{% block header_text %}{% endblock %}</h1>
          {% block extra_header %}
          {% endblock %}
        </div>
      </div>

          {% block content %}
          {% endblock %}

    </div>

    {% block scripts %}
    {% endblock %}
  </body>

</html>

src/lists/templates/form.html
<form method="POST" action="{{ form_action }}">
    {% csrf_token %}
    <input
      id="id_text"
      name="text"
      class="form-control
             form-control-lg
             {% if form.errors %}is-invalid{% endif %}"
      placeholder="Enter a to-do item"
      value="{{ form.text.value }}"
      aria-describedby="id_text_feedback"
      required
    />
    {% if form.errors %}
      <div id="id_text_feedback" class="invalid-feedback">
        {{ form.errors.text.0 }}
      </div>
    {% endif %}
  </form>

src/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block extra_header %}
  {% url 'new_list' as form_action %}
  {% include "form.html" with form=form form_action=form_action %}
{% endblock %}

{% block scripts %}
  {% include "scripts.html" %}
{% endblock %}

src/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block extra_header %}
  {% url 'view_list' list.id as form_action %}
  {% include "form.html" with form=form form_action=form_action %}
{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-lg-6"></div>
    <table class="table" id="id_list_table">
      {% for item in list.item_set.all %}
        <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
      {% endfor %}
    </table>
  </div>
</div>

<h4>Share this list:</h4>
<form method="POST" action="{% url 'share_list' list.id %}">
  {% csrf_token %}
  <input class="form-control" name="sharee" placeholder="your-friend@example.com"/>
  <button type="submit" class="btn btn-primary mt-2">Share</button>
</form>

{% if list.owner %}
  <h4>List owner:</h4>
    <p id="id_list_owner">{{ list.owner.email }}</p>
{% endif %}

<h4>Shared with:</h4>
<ul>
  {% for sharee in list.shared_with.all %}
    <li class="list-sharee">{{ sharee.email }}</a></li>
  {% endfor %}
</ul>

{% endblock %}

{% block scripts %}
  {% include "scripts.html" %}
{% endblock %}

src/lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}{{user.email}}'s Lists{% endblock %}

{% block content %}
  <h2>{{ owner.email }}'s lists</h2>
  <ul>
    {% for list in owner.lists.all %}
      <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
    {% endfor %}
  </ul>

  <h2>Lists shared with {{ owner.email }}</h2>
  <ul>
    {% for list in owner.shared_lists.all %}
    <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

src/lists/templates/scripts.html
<script src="/static/lists.js"></script>

<script>
  window.onload = () => {
    initialize("#id_text");
  };
</script>